#!/usr/bin/env bash
# Render shairport-sync.conf from environment variables.
#
# Required env: AIRPLAY_NAME
# Required env when MQTT_ENABLED is truthy: MQTT_HOST
# Optional env: MQTT_ENABLED (default yes), MQTT_PORT (default 1883),
#               MQTT_USER, MQTT_PASSWORD, MQTT_TOPIC
#
# Usage: render-config.sh <output-path>
#   e.g.  render-config.sh /out/shairport-sync.conf

set -euo pipefail

: "${AIRPLAY_NAME:?AIRPLAY_NAME required}"

out="${1:-/dev/stdout}"

# Parse MQTT_ENABLED into a boolean. Accepts the common truthy/falsy forms.
mqtt_enabled_raw="${MQTT_ENABLED:-yes}"
case "${mqtt_enabled_raw,,}" in
    yes|true|1|on)        mqtt_enabled=1 ;;
    no|false|0|off|"")    mqtt_enabled=0 ;;
    *)
        echo "MQTT_ENABLED must be yes/no/true/false/1/0/on/off (got: '$mqtt_enabled_raw')" >&2
        exit 1
        ;;
esac

# Escape a value for safe embedding inside a libconfig double-quoted string:
# backslash and double-quote must be escaped. (See libconfig grammar.)
libconfig_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    printf '%s' "$s"
}

AIRPLAY_NAME_ESC="$(libconfig_escape "$AIRPLAY_NAME")"

if [[ $mqtt_enabled -eq 1 ]]; then
    : "${MQTT_HOST:?MQTT_HOST required when MQTT_ENABLED=yes}"
    : "${MQTT_PORT:=1883}"
    if ! [[ "$MQTT_PORT" =~ ^[0-9]+$ ]]; then
        echo "MQTT_PORT must be an integer (got: '$MQTT_PORT')" >&2
        exit 1
    fi
    MQTT_HOST_ESC="$(libconfig_escape "$MQTT_HOST")"
    MQTT_USER_ESC="$(libconfig_escape "${MQTT_USER:-}")"
    MQTT_PASSWORD_ESC="$(libconfig_escape "${MQTT_PASSWORD:-}")"
    MQTT_TOPIC_ESC="$(libconfig_escape "${MQTT_TOPIC:-}")"
fi

{
    cat <<EOF
// Generated by render-config.sh from .env. Do not hand-edit; changes
// will be overwritten on the next \`docker compose up\`.

general = {
    name = "${AIRPLAY_NAME_ESC}";
    output_backend = "pulseaudio";

    // Hold playback at unity gain so LedFx FFT sees consistent levels
    // regardless of what the AirPlay sender sets its volume to. Volume
    // control still happens at the speaker side.
    ignore_volume_control = "yes";

    interpolation = "auto";
};

EOF

    if [[ $mqtt_enabled -eq 1 ]]; then
        cat <<EOF
mqtt = {
    enabled = "yes";
    hostname = "${MQTT_HOST_ESC}";
    port = ${MQTT_PORT};${MQTT_USER:+
    username = \"${MQTT_USER_ESC}\";}${MQTT_PASSWORD:+
    password = \"${MQTT_PASSWORD_ESC}\";}${MQTT_TOPIC:+
    topic = \"${MQTT_TOPIC_ESC}\";}

    // Publish play_start, play_end, play_flush, play_resume + per-track
    // metadata (title, artist, album, ...) under <topic>/<event>.
    publish_parsed = "yes";

    // Publish HA-MQTT-discovery messages so a media_player entity appears
    // in Home Assistant automatically, no manual entity setup.
    enable_autodiscovery = "yes";
    autodiscovery_prefix = "homeassistant";
};

EOF
    fi

    cat <<EOF
pulseaudio = {
    server = "unix:/tmp/pulseaudio.socket";
    // sink is intentionally not set: shairport falls back to the PulseAudio
    // server's default sink, which is the "auto_null" sink created by
    // LedFx's module-always-sink. Setting sink="" here causes shairport's
    // PA backend to fail with PA_BAD_STATE on stream connect.
};

diagnostics = {
    log_verbosity = 1;  // 0 silent, 1 normal, 2 verbose, 3 very verbose
};
EOF
} > "$out"

if [[ $mqtt_enabled -eq 1 ]]; then
    echo "Rendered shairport-sync.conf to $out (MQTT enabled, host=$MQTT_HOST)"
else
    echo "Rendered shairport-sync.conf to $out (MQTT disabled)"
fi
